language: java
jdk:
  - openjdk17

addons:
  sonarcloud:
    organization: "onoprienko-viktoria"
    token:
      secure: "Nd6Dp3HeEJQPMk6MuooIC0e4w6HzCYzEUK4y8GBTbGTsqLbs6RwK4ePC8g697hm5aZf7LzBYZerL8yqagqqYeHENLwtNlvY79ypB7QCt+xzC6emsi6degNkye44yXRXL7Q9ormgg4p4DzElGsNvrX9bcxVVsXkvxTTd3EHX5pJY4UJ8Lp7B90H/pHpvpDN3b5hx0X1B0ih6G7hhrTqEqi0Yp2PiOkSU4YBTB7WGAeKui7j5KLG+A9hDm+00z9RHmdIB0NqU44zJfTcCD/8n4UfqAQUSyRhqaUX6rGGGQ5aO2Ia9CWOrqVn/4JaIhfe5oF12QGksCyktkQ8rEg494jXxP2prUgHrJyOEZWSe2p43gk2b40+67wXd5hXq/8gnz1f3PMom36K1/2x1rqTcnC8P0chwy0hm67E7t3OXFikA20v6iDfTfO0g/qij6ep0Wi9s2wRkhWnMeOnQIdaVH5Ap0O/LXDyULKeChsvIjFD7qMBF6G4DIUnmsYzPqjKtkL+XJ3zoDbOPM+C5bKaNxQZsj5IP2Dc/Fi1LVtxA0U0JJ9LoeIXQx/e1SJiXumFzlcEzidPOa581WoYyD/AfBJBvdFHZxR6Ud6LFavVdy1yIcVuowNY1nMV6b3CLleHm0GqlCe7pJb+871/8xUSr0Doi/S5RlmJJzOrmX8flbZGg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Onoprienko-Viktoria_movieland