language: java
jdk:
  - openjdk17

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "onoprienko-viktoria"
    token:
      secure: "fWfQlo5cckCXo/QOwE8pqY/cpAvn60G271cnJ9yvJaFskNNGUzZzvSM7rjvJVE0enzikEY95EfsmPcgRY4mZfxjgHndCvCQJgcSCh9gKyPKh4dojK45JWsYGRBSsERMjlSaxbrUW1FOH8dpF10GKWQa/Cg7lG1BKE52BsUplQ8YmmuM3oX/hgw6uu/6qaa+KZ+VKdcCA+KGifRXze+wV3PcDb18RzmNiLcbfOZNgyp2OKTTGfpJ3M+ifSEu7f5ZGwNaxVHgpNBvH8gjkcKQEIZPu0gcKWJ/gTS3pC+Cx91q3tEYKEIy/YyCViteh6SZlMv0t5BxUH0mI0bvf6VgB6qtemNPewyHEB0YeEgAYHG+DTDOeOSYaOK4EKuej87lsYU1WCuMQ69a101XagEfY4O9oVmNGQ5e6jKVxiwsgZ6JaLDC4HvrchldyqM1gaBaRzIKJTbGzzzvgJ1fFiDYJMTvm0AZWC7OvwXFzPTkr+neZrD/QZcArna8qWzDhdCd1PgGUC+FvEzXDxo1Sh2FTqVtDB9jBdD1WYYRtWOsxDFgIKBIZkAq1NUR6ZI3DlgucYBgvboCDsi3TcZEUlLY2UGpftdCFBrq66HTSL+PawPPQeS2pl33kUm/1hQNBGLYgEepRpgkY1WIyj70OwC/H94ha9Uj6+k/IU0N23B1HPcU="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Onoprienko-Viktoria_movieland